package main

import (
	"bytes"
	"encoding/json"
	"os"
	"sort"
	"strings"
	"testing"
)

// The release provider (scripts/mel-release-provider.py) estate-scans every
// catalog manifest and selection receipt it reads. It is Python and cannot run
// storeProductionForbiddenValues, so it reads that derivation's committed
// rendering instead, and this test keeps the two identical: the provider's
// forbid set is the Store's, never a narrower hand-kept copy.
const (
	retiringEstateValuesFile   = "../../fleet/retiring-estate-values.json"
	retiringEstateValuesSchema = "melusina-retiring-estate-values/v1"
	// Set to 1 to rewrite the file from the derivation.
	retiringEstateValuesWriteEnv = "MELUSINA_WRITE_RETIRING_ESTATE_VALUES"
)

type retiringEstateValuesDocument struct {
	Schema string            `json:"schema"`
	Source string            `json:"source"`
	Values map[string]string `json:"values"`
}

func renderRetiringEstateValues(t *testing.T, values map[string]string) []byte {
	t.Helper()
	raw, err := json.MarshalIndent(retiringEstateValuesDocument{
		Schema: retiringEstateValuesSchema,
		Source: "generated by sidecar/melusina-store-sidecar TestRetiringEstateValuesFileIsTheStoreForbidSet from storeProductionForbiddenValues; regenerate, never edit",
		Values: values,
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return append(raw, '\n')
}

func TestRetiringEstateValuesFileIsTheStoreForbidSet(t *testing.T) {
	derived := storeProductionForbiddenValues(t)
	want := renderRetiringEstateValues(t, derived)
	if os.Getenv(retiringEstateValuesWriteEnv) == "1" {
		if err := os.WriteFile(retiringEstateValuesFile, want, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile(retiringEstateValuesFile)
	if err != nil {
		t.Fatalf("retiring-estate-values-file-missing: %v (regenerate with %s=1)", err, retiringEstateValuesWriteEnv)
	}
	if bytes.Equal(got, want) {
		return
	}
	var committed retiringEstateValuesDocument
	if err := json.Unmarshal(got, &committed); err != nil {
		t.Fatalf("retiring-estate-values-file-malformed: %v", err)
	}
	var drift []string
	for field, value := range derived {
		if committed.Values[field] != value {
			drift = append(drift, "derived "+field)
		}
	}
	for field := range committed.Values {
		if _, ok := derived[field]; !ok {
			drift = append(drift, "committed-only "+field)
		}
	}
	sort.Strings(drift)
	t.Fatalf("retiring-estate-values-file-drift: fleet/retiring-estate-values.json is not storeProductionForbiddenValues (%s); regenerate with %s=1 go test -run TestRetiringEstateValuesFileIsTheStoreForbidSet",
		strings.Join(drift, ", "), retiringEstateValuesWriteEnv)
}
